
server:
  port: 9004

spring:
  application:
    name: sessionService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka