server:
  port: 8011

spring:
  application:
    name: boardService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/project1db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cossafyco
  #    url: jdbc:mysql://localhost:3306/project1db?serverTimezone=UTC&characterEncoding=UTF-8
  #    password: 1234
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://i8a703.p.ssafy.io:8761/eureka