server:
  port: 8000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://EurekaDiscoveryService:8761/eureka

jwt:
  secret: PorkCurtletFriedChickenSundubuJJigaeGrilledPorkBelly


spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://i8a703.p.ssafy.io:443'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: board
          uri: http://BoardService:8011/
          predicates:
            - Path=/board/**
        - id: comment
          uri: http://BoardService:8011/
          predicates:
            - Path=/comment/**
        - id: member
          uri: http://MemberService:8012/
          #          uri: http://localhost:8012/
          predicates:
            - Path=/member/changePassword, /member/delete/**, /member/logout, /member/extract
            - Method=POST
          filters:
            - AuthenticationHeaderFilter
        - id: member
          uri: http://MemberService:8012/
          #          uri: http://localhost:8012/
          predicates:
            - Path=/member/info/**
          filters:
            - AuthenticationHeaderFilter
        - id: member
          #          uri: http://localhost:8012/
          uri: http://MemberService:8012/
          predicates:
            - Path=/member/**
        - id: uniqueCheck
          #          uri: http://localhost:8012/
          uri: http://MemberService:8012/
          predicates:
            - Path=/check/**
        - id: sessionFunction
          uri: http://SessionFunctionService:8013/
          predicates:
            - Path=/sessionFunction/**
        - id: session
          uri: http://SessionService:8014/
          predicates:
            - Path=/session/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://mysql:3306/project1db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    password: cossafyco
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
    database: mysql
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
  data:
    web:
      pageable:
        one-indexed-parameters: true

