spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: mysql
  devtools:
    livereload:
      enabled: true
  application:
    name: shopService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cossafyco
    url: jdbc:mysql://mysql:3306/project1db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot: ERROR
        security: DEBUG
      apache:
        tiles: INFO
    root: INFO
  file:
    name: './fileUpload-BE.log'
eureka:
  client:
    register-with:
      eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://EurekaDiscoveryService:8761/eureka
server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  port: 8019
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,multipart/form-data

springfox:
  documentation:
    swagger:
      use-model-v3: false
