server:
  port: 9002


spring:
  application:
    name: boardService



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://i8a703.p.ssafy.io:8761/eureka

