
server:
  port: 8014

spring:
  application:
    name: sessionfunctionService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://EurekaDiscoveryService:8761/eureka