
server:
  port: 8013

spring:
  application:
    name: SessionFunctionService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://EurekaDiscoveryService:8761/eureka