server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      routes:
        - id: sessionFunction
          uri: http://localhost:9001/
          predicates:
            - Path=/sessionFunction/**
        - id: board
          uri: http://localhost:9002/
          predicates:
            - Path=/board/**
        - id: member
          uri: http://localhost:9003/
          predicates:
            - Path=/member/**
        - id: session
          uri: http://localhost:9004/
          predicates:
            - Path=/session/**
